export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{background:'green', padding:'20px', textAlign:'center'}}>
          <p>
            Header
          </p>
        </header>
        {children}
        <footer style={{background:'green', padding:'20px', textAlign:'center'}}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
